services:
  nginx:
    image: nginx:latest
    container_name: tracker-nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

  php:
    image: php:8.4-fpm
    container_name: tracker-php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:latest
    container_name: tracker-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tracker_user
      MYSQL_PASSWORD: tracker_password
      MYSQL_DATABASE: tracker

volumes:
  mysql_data: